AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: >
  Serverless Translator

  A serverless REST API for translating text using AWS services.

Globals:
  Function:
    Runtime: python3.12
    Timeout: 10
    MemorySize: 128
    Architectures:
      - x86_64

Resources:

  TranslatorFunction:
    Type: AWS::Serverless::Function

    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
    
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - translate:TranslateText
              Resource: "*"

      Events:
        TranslateApi:
          Type: Api
          Properties:
            Path: /translate
            Method: post    
            
Outputs:

  ApiEndpoint:
    Description: REST API endpoint
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/translate"

  TranslatorFunctionArn:
    Description: Translator Lambda ARN
    Value: !GetAtt TranslatorFunction.Arn